#!/sbin/runscript
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

LOGFILE="/var/log/libreoffice-online/lool.log"
ERRFILE="/var/log/libreoffice-online/lool-err.log"
PIDFILE="/var/run/lool.pid"

depend() {
	use clock logger
	#need localmount
}

check_start() {
	local MYPATH="/var/lib/libreoffice-online/systemplate"
	if [ ! -d "${MYPATH}" ]; then
		echo "Directory '${MYPATH}' does not exists"
		exit 1
	fi
}

start() {
	ebegin "Starting libreoffice-online"
	check_start
	start-stop-daemon \
		--start \
		-u lool \
		--background \
		--make-pidfile \
		--pidfile "${PIDFILE}" \
		--stdout "${LOGFILE}" \
		--stderr "${ERRFILE}" \
		--exec /usr/bin/loolwsd
	eend $?
}

stop() {
	ebegin "Stopping libreoffice-online"
	start-stop-daemon --stop --pidfile "${PIDFILE}"
	eend $?
}
